services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fmcsa_db
    volumes:
      - "./fmcsa_records:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  app:
    build: .
      - pgdatabase
    environment:
      DATABASE_HOST: pgdatabase
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"